/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package U2_Acceso;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Darking
 */
public class Acceso extends javax.swing.JFrame {

    ArrayList<String> Usuarios = new ArrayList<>();
    ArrayList<String> PassWord = new ArrayList<>();
    
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        Generar();
    }
    
        private void Generar(){
            
        Usuarios.add("Alex");
        Usuarios.add("Gerardo");
        Usuarios.add("Gema");
        Usuarios.add("Nataly");
        Usuarios.add("Armando");
        Usuarios.add("Ana");
        Usuarios.add("Sandra");
        
        PassWord.add("a2020");
        PassWord.add("Gera2020");
        PassWord.add("Gem2020");
        PassWord.add("N2020");
        PassWord.add("Arm2020");
        PassWord.add("Ana2020");
        PassWord.add("S2020");
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAcceder = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pswContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Contraseña");

        btnAcceder.setText("Acceder");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        btnAcceder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAccederKeyPressed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(pswContraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceder)
                    .addComponent(btnCancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        Acceder();
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnAccederKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAccederKeyPressed
        // TODO add your handling code here:
        Acceder();
    }//GEN-LAST:event_btnAccederKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        Cancelar();
    }//GEN-LAST:event_btnCancelarKeyPressed

    boolean Respuesta = true;
    
    private void Verificar(String UsrIntroducido, String PssIntroducido){
       
        for(int x = 0  ; x<Usuarios.size(); x++){
            String UsrActual = Usuarios.get(x);
            if(UsrIntroducido.equals(UsrActual)){
                String PssActual = PassWord.get(x);
                if(PssIntroducido.equals(PssActual)){
                    Respuesta = true;
                    break;
                }else{
                   Respuesta = false;
                    break;
                }
            }else{
                Respuesta = false;
            }
        }
    }
    
    
    private void Cancelar(){
        JOptionPane.showMessageDialog(null,"Operacion cancelada" );
        txtNombre.setText(null);
        pswContraseña.setText(null);
        txtNombre.requestFocus();
    }
    
    private void Acceder(){
        String strNombre, pswPasswor, strResultado;
        strNombre = txtNombre.getText();
        pswPasswor = new String(pswContraseña.getPassword());
        
        Verificar(strNombre, pswPasswor);
        
        if(Respuesta == true){
            strResultado = "Acceso concedido";
            this.setVisible(false);
            //abrir un JFrame            
            Fibo Num = new Fibo();
            Num.setVisible(true);
            JOptionPane.showMessageDialog(null,strResultado );
        }else{
            strResultado = "Acceso denegado";
            JOptionPane.showMessageDialog(null,strResultado );
        }
        
       /* if (strNombre.equals("Alex") && pswPasswor.equals("A1020")){
            strResultado = "Acceso concedido";
            this.setVisible(false);
            //abrir un JFrame            
            Fibo Num = new Fibo();
            Num.setVisible(true);
            JOptionPane.showMessageDialog(null,strResultado );
                    }
        else{
            strResultado = "Acceso denegao";
            JOptionPane.showMessageDialog(null,strResultado );
        }
        */
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Acceso().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
